mysite/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
        path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
        #django.contrib.auth 사용할거라 중간에 auth~~씀, view안씀 > view를 안쓰니까 templates/.html을 바로 연결해야됨 :html안만들고 기본틀로 생성
        path('logout/' , auth_views.LogoutView.as_view(),name='logout'),
        #as_view() 공백인 이유는 로그인은  로그인 html로 넘어가야 하지만, 로그아웃은 그냥 홈화면으로 돌아가면 됨
        path('signup/' , views.signup, name='signup'),

]

mysite/mysite/config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo .views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),  #파이보 경로 추가
    path('common/',include('common.urls')), #common 경로 추가
    path('',base_views.index, name='index'),  #로그인,아웃 성공시 /pybo 가아니라 그냥 localhost:8000 으로감 > setting에서 설정된
]

mysite/mysite/pj/pj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/mysite/pybo/urls.py
from django.urls import path
from .views import base_views, maincont_views, comment_views, vote_views  #기존에는 from .import views

app_name = 'pybo'  #다른 프로젝트 추가될수도 있으니 앱 네임 지정

urlpatterns = [

    # html 작성 > urls에 먼저 작성 > views에 함수 작성
    # 'name' 을 넣어서 사이트주소 특정지음

    #base_views.py
    path('',base_views.index, name='index'), #views.py로 이동 / index함수이동
    path('<int:maincont_id>/',base_views.detail, name='detail'), #각 사이트들을 눌렀을때 id를 인식함 > views.py로이동 / detail함수이동

    #maincont_views.py
    path('maincont/create/',maincont_views.maincont_create, name='maincont_create'), #추가저장 하는거 path만들어주기
    path('maincont/modify/<int:maincont_id>/' , maincont_views.maincont_modify , name='maincont_modify'), #글 수정하는창
    path('maincont/delete/<int:maincont_id>/', maincont_views.maincont_delete, name='maincont_delete'), #글 삭제

    #comment_views.py
    path('comment/create/maincont/<int:maincont_id>/',comment_views.comment_create_maincont, name='comment_create_maincont'), #댓글생성
    path('comment/modify/maincont/<int:comment_id>/',comment_views.comment_modify_maincont, name='comment_modify_maincont'), #댓글수정
    path('comment/delete/maincont/<int:comment_id>/',comment_views.comment_delete_maincont, name='comment_delete_maincont'), #댓글삭제

    #vote_views.py
    path('vote/maincont/<int:maincont_id>/',vote_views.vote_maincont, name='vote_maincont'),  #추천기능

]

mysite/mysite/common/models.py
from django.db import models

# Create your models here.

mysite/mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username","email")

mysite/mysite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm   #forms.py의 UserForm 함수 사용 : 상속 //from,import 사용해서 연동

def signup(request):

     # 가입 버튼클릭했을때 첫 화면 띄우는건 GET ,  회원 객체 생성하는건 POST
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')   # .cleaned 는 입력한 값을 얻기위헤 사용하는 함수
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username , password=raw_password)  # authenticate 와 login(r,u) 는 자동 로그인
            login(request,user)
            return redirect('index')
    else:   #GET
        form = UserForm()
    return render(request, 'common/signup.html',{'form': form})

mysite/mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">

  <div class="row">
    <div class="col-4">
      <h4>로그인</h4>
    </div>

    <div class="col-8 text-right">
      <span>
        또는   <a href="{% url 'common:signup' %}"> 계정을 만드세요.</a>
      </span>
    </div>
  </div>



  <form method="post" class="post-form" action="{% url 'common:login' %}">

    {% csrf_token %}

    <!--로그인 성공 후 이동되는 url-->
    <input type="hidden" name="next" value="{{ next }}">

    {% include "form_errors.html" %} <!--로그인에 실페한 원인을 알려준다.-->
    <div class="form-group">

      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username"
        >
    </div>

    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password"
       >
    </div>

    <button type="submit" class="btn btn-primary">로그인</button>

  </form>
</div>

{% endblock %}

mysite/mysite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
  <div class="row my-3">
    <div class="col-4">
      <h4>회원가입</h4>
    </div>
    <div class="col-8 text-right">
      <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a> </span>
    </div>
  </div>

  <form method="post" class="post-form">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="username">사용자 이름</label>
      <input type="text" class="form-control" name="username" id="username">
    </div>

    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input type="password" class="form-control" name="password1" id="password1" >
    </div>

    <div class="form_group">
      <label for="password2">비밀번호 확인</label>
      <input type="password" class="form-control" name="password2" id="password2" >
    </div>

    <div class="form-group">
      <label for="email">이메일</label>
      <input type="text" class="form-control" name="email" id="email"  >
    </div>
    <button type="submit" class="btn btn-primary">가입하기</button>
  </form>

</div>

{% endblock %}