mysite/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
        path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
        #django.contrib.auth 사용할거라 중간에 auth~~씀, view안씀 > view를 안쓰니까 templates/.html을 바로 연결해야됨 :html안만들고 기본틀로 생성
        path('logout/' , auth_views.LogoutView.as_view(),name='logout'),
        #as_view() 공백인 이유는 로그인은  로그인 html로 넘어가야 하지만, 로그아웃은 그냥 홈화면으로 돌아가면 됨
        path('signup/' , views.signup, name='signup'),

]

mysite/mysite/config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo .views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),  #파이보 경로 추가
    path('common/',include('common.urls')), #common 경로 추가
    path('',base_views.index, name='index'),  #로그인,아웃 성공시 /pybo 가아니라 그냥 localhost:8000 으로감 > setting에서 설정된
]

mysite/mysite/pj/pj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/mysite/pybo/urls.py
from django.urls import path
from .views import base_views, maincont_views, comment_views, vote_views  #기존에는 from .import views

app_name = 'pybo'  #다른 프로젝트 추가될수도 있으니 앱 네임 지정

urlpatterns = [

    # html 작성 > urls에 먼저 작성 > views에 함수 작성
    # 'name' 을 넣어서 사이트주소 특정지음

    #base_views.py
    path('',base_views.index, name='index'), #views.py로 이동 / index함수이동
    path('<int:maincont_id>/',base_views.detail, name='detail'), #각 사이트들을 눌렀을때 id를 인식함 > views.py로이동 / detail함수이동

    #maincont_views.py
    path('maincont/create/',maincont_views.maincont_create, name='maincont_create'), #추가저장 하는거 path만들어주기
    path('maincont/modify/<int:maincont_id>/' , maincont_views.maincont_modify , name='maincont_modify'), #글 수정하는창
    path('maincont/delete/<int:maincont_id>/', maincont_views.maincont_delete, name='maincont_delete'), #글 삭제

    #comment_views.py
    path('comment/create/maincont/<int:maincont_id>/',comment_views.comment_create_maincont, name='comment_create_maincont'), #댓글생성
    path('comment/modify/maincont/<int:comment_id>/',comment_views.comment_modify_maincont, name='comment_modify_maincont'), #댓글수정
    path('comment/delete/maincont/<int:comment_id>/',comment_views.comment_delete_maincont, name='comment_delete_maincont'), #댓글삭제

    #vote_views.py
    path('vote/maincont/<int:maincont_id>/',vote_views.vote_maincont, name='vote_maincont'),  #추천기능

]

mysite/mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User  #계정 연결
#models.py는 전체적인 틀(구성), forms.py는 입력하는 객체

class Maincont(models.Model):

    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_maincont')  #계정이 삭제되면 관련데이터 삭제 / author 추가

    modify_date = models.DateTimeField(null=True, blank=True)  #데이터 수정일시 의미 (값을 비워두어도된다)

    subject=models.TextField() #url
    sentence=models.TextField()#요약문장
    word=models.TextField()#요약단어
    create_date=models.DateTimeField()#작성날짜

    voter=models.ManyToManyField(User, related_name='voter_maincont') #게시글 추천기능

    def __str__(self):
        return self.subject     #출력시 제목표시


class Comment(models.Model):                                    #댓글 모델
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()
    modify_date=models.DateTimeField(null=True, blank=True)
    maincont=models.ForeignKey(Maincont, null=True, blank=True, on_delete=models.CASCADE) #이 댓글이 달린 질문 / on_delete : subject삭제시 같이 삭제



# Create your models here.

mysite/mysite/pybo/forms.py
from django import forms
from pybo.models import Maincont , Comment

class MaincontForm(forms.ModelForm):
    class Meta:
        model = Maincont
        fields = ['subject','word','sentence'] #사이트url, 단어, 문장을 폼의 필드로 가짐
        #subject >제목 / word >단어 / sentence >문장   : 한글로 바꾸기
        labels = {
            'subject':'제목',
            'word':'단어',
            'sentence':'문장',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content'] #댓글작성하는 폼
        labels={
            'content':'댓글내용',
        }

mysite/mysite/pybo/views/base_views.py
#기본 ( index창 , detail창)
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from django.db.models import Q, Count   #OR 조건으로 데이터를 검색하는 장고의 함수

from ..models import Maincont  #점 두개(..)인 이유는 pybo/views/ 두번에 걸쳐서 있음
#기존의 view.py에서 가져옴

def index(request):     #창열어주기

    page = request.GET.get('page', '1')  # 1페이지을 기본으로 출력 > localhost:8000/pybo/?page1
    kw = request.GET.get('kw','')        # localhost:8000/?kw=검색어&page=3
    sr = request.GET.get('sr','recent')  #정렬기준

    if sr =='recommend':  # 추천순
        maincont_list = Maincont.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')

    elif sr =='recent':  # 최신순
        maincont_list = Maincont.objects.order_by('-create_date')


    if kw:                                                      #검색하는 함수
        maincont_list=maincont_list.filter(
            Q(subject__icontains=kw)|     #url로 검색
            Q(word__icontains=kw)|         #단어로 검색
            Q(sentence__icontains=kw)|    #문장으로 검색
            Q(author__username__icontains=kw)       #글쓴이로 검색

        ).distinct()



    #페이징 처리
    paginator = Paginator(maincont_list, 10)    #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)             #페이지 가져오기

    context = {'maincont_list': page_obj, 'page':page, 'kw':kw, 'sr':sr}    #kw(검색어)와 page도 반환
    return render(request, 'pybo/maincont_list.html',context)  #render함수 이용해서 html에 context내용 넣음
    #결과물 : 페이지 1에서 10개의 저장된데이터만 화면에 나타난다.



def detail(request, maincont_id):    #사이트 클릭했을때(id로) 다음창으로 넘어가도록 구현

    maincont=get_object_or_404(Maincont, pk=maincont_id)
    context={'maincont':maincont}

    return render(request,'pybo/maincont_detail.html',context)

mysite/mysite/pybo/views/comment_views.py
#댓글 관리 (생성 , 수정 , 삭제)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render , get_object_or_404 , redirect , resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Maincont , Comment


@login_required(login_url='common:login')
def comment_create_maincont(request , maincont_id):                             #<댓글추가>
    maincont=get_object_or_404(Maincont, pk=maincont_id)  #게시판 글 번호
    if request.method =="POST":
        form=CommentForm(request.POST) #comment form을 가져옴
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.maincont=maincont
            comment.save()
            #댓글 앵커 return / maincont_id=comment.maincont.id 그러나 maincont.id 해도 상관 없지않나..?
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', maincont_id=comment.maincont.id), comment.id))
            #return redirect('pybo:detail',maincont_id=maincont.id)  기존 리턴 > 댓글앵커 전
    else:
        form=CommentForm()
    context={'form':form}
    return render(request, 'pybo/comment_form.html',context)


@login_required(login_url='common:login')
def comment_modify_maincont(request, comment_id):                           #<댓글수정>
    comment=get_object_or_404(Comment,pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정 권한이 없습니다.')
        return redirect('pybo:detail',maincont_id=comment.maincont.id)  #comment의 maincont의 id > comment의 model 확인, 이댓글이 달린 게시글의 아이디로  간다.
                                                                        #comment의 id는 댓글번호(몇번째인지) _ maincont의 id는 게시글이 몇번째 인지
    if request.method == "POST":   #POST : 댓글업데이트
        form=CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.modify_date=timezone.now()
            comment.save()
        # 댓글 앵커 return / maincont_id=comment.maincont.id 얘는 model.py에서 가져오는 거라 comment.maincont.id를 꼭해야됨 , 그냥 maincont.id 인식안됨
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', maincont_id=comment.maincont.id), comment.id))
           # return redirect('pybo:detail',maincont_id=comment.maincont.id) 기존 리턴 > 앵커 없음

    else:   #GET : 댓글조회
       form=CommentForm(instance=comment)  #instance=comment:이전에 있던 내용 가져옴

    context={'form':form}
    return render(request,'pybo/comment_form.html',context)



@login_required(login_url='common:login')
def comment_delete_maincont(request, comment_id):
    comment=get_object_or_404(Comment, pk=comment_id)                           #<댓글삭제>
    if request.user != comment.author:
        messages.error(request,'댓글삭제 권한이 없습니다.')
        return redirect('pybo:detail',maincont_id=comment.maincont.id)
    else:
        comment.delete()
    return redirect('pybo:detail',maincont_id=comment.maincont.id)

mysite/mysite/pybo/views/maincont_views.py
#게시글 관리 (생성 , 수정 , 삭제)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render , get_object_or_404, redirect
from django.utils import timezone

from ..forms import MaincontForm
from ..models import Maincont


@login_required(login_url='common:login') # 웹활동전에 로그인 여부 검사 , 만일 안돼있으면 로그인 창으로 넘어감
def maincont_create(request):
    if request.method == 'POST':       #데이터 저장
        form = MaincontForm(request.POST)
        if form.is_valid():             #폼이 유효한지
            maincont = form.save(commit=False)    #데이터 False:임시저장                         #<게시글작성>
            maincont.author = request.user     #추가한 author속성 적용 (추가)
            maincont.create_date = timezone.now()  #날짜 받아옴
            maincont.save()                        #데이터 완전저장
            return redirect('pybo:index')   #index 화면으로 돌아감

    else:       #request.method =='GET' / 추가등록 버튼클릭
        form=MaincontForm()
    context = {'form' : form}
    return render(request, 'pybo/maincont_form.html',context)    #폼 객체 띄워줌


@login_required(login_url='common:login')
def maincont_modify(request, maincont_id):
    maincont = get_object_or_404(Maincont, pk=maincont_id)                                #<게시글 수정>

    if request.user != maincont.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', maincont_id=maincont_id)

    if request.method == "POST":
        form=MaincontForm(request.POST, instance=maincont) # instance=maincont:기존저장상태에서 수정 / request.POST:수정함 (덮어씌움)
        if form.is_valid():
            maincont=form.save(commit=False)  #폼 임시 저장 1
            maincont.author=request.user      #사용자 같은지 확인 2
            maincont.modify_date=timezone.now() #수정일시 저장
            maincont.save()                     # 2확인 했으니 1을 영구저장으로바꿈
            return redirect('pybo:detail', maincont_id=maincont.id)    #수정하기 버튼 누르면 detail.html로 돌아감 , index.html 아님

    else:
        form=MaincontForm(instance=maincont)

    context={'form' : form}
    return render(request, 'pybo/maincont_form.html',context)

@login_required(login_url='common:login')
def maincont_delete(request , maincont_id):
    maincont=get_object_or_404(Maincont, pk=maincont_id)                        #<게시글 삭제기능>
    if request.user != maincont.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', maincont_id=maincont.id)
    else:
        maincont.delete()
    return redirect('pybo:index')

mysite/mysite/pybo/views/vote_views.py
#추천기능

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Maincont

@login_required(login_url='common:login')
def vote_maincont(request, maincont_id):
    maincont=get_object_or_404(Maincont, pk=maincont_id)
    if request.user == maincont.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        maincont.voter.add(request.user)
    return redirect('pybo:detail',maincont_id=maincont.id)

mysite/mysite/templates/pybo/comment_form.html
{% extends 'base.html' %}   <!--댓글등록 폼-->
{% block content %}

<div class="container my-3">
  <h5 class="border-bottom pb-2">댓글 등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">댓글내용</label>
      <textarea class="form-control" name="content" id="content" rows="3">
        {{ form.content.value|default_if_none:'' }}
      </textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>

{% endblock %}

<!--form.content.value|default_if_none:'' -->

mysite/mysite/templates/pybo/maincont_detail.html
{% extends 'base.html' %}    <!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->
{% block content %}        <!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->
{% load pybo_filter %}

<div class="container my-3">

    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>                          <!--사용자 자가추천 오류 표시-->
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom py-2">{{ maincont.subject }}</h2>   <!--제목-->


    <div class="row my-3">

        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ maincont.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_maincont' maincont.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a> <!--추천버튼을 누르는 이벤트를 얻기 위한 클래스-->
        </div>

        <div class="col-11">

    <h4>{{ maincont.word }}</h4>                                    <!--단어-->

    <div class="card">
        <div class="card-body">
        <div class="card-text">
            {{ maincont.sentence|mark }}                                     <!--문장 / 마크다운으로 표시가능-->
        </div>
        <div class="d-flex justify-content-end">

            {% if maincont.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">마지막 수정시간</div>                             <!--수정 시간-->
                <div> {{ maincont.modify_date }} </div>
            </div>
            {% endif %}

            <div class="badge badge-light p-2 text-left">
                <div class="mb-2">{{ maincont.author.username }}</div>
                <div>{{ maincont.create_date }}</div>                              <!--날짜-->
            </div>

        </div>


        {% if request.user == maincont.author %}    <!--수정하려는 유저와 로그인한 유저가 같을때만 보여지는 블럭-->
        <div class="my-3">
            <a href="{% url 'pybo:maincont_modify' maincont.id %}"
            class="btn btn-sm btn-outline-secondary "> 수정 </a>                      <!--게시글 수정버튼-->

            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'pybo:maincont_delete' maincont.id %}"> 삭제 </a>         <!--게시글 삭제버튼-->


        </div>
           {% endif %}


         <div class="iframe_site"
         style=" border: 1px solid; width:100%; height:400px; " >          <!--사이트 아이프레임 들어감-->
        아이프레임 사이트</div>




        {% if maincont.comment_set.count > 0 %}                                         <!--댓글 작성-->
        <div class="mt-3">
            {% for comment in maincont.comment_set.all %}
            <a name = "comment_{{ comment.id }}"></a>    <!--댓글 앵커 추가-->
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>


                    {% if request.user == comment.author %}
                    <div class="suj">
                    <a href="{% url 'pybo:comment_modify_maincont' comment.id %}" class="small">수정</a>
                    </div>

                    <div class="sak">
                    <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_maincont' comment.id %}">삭제</a>
                    </div>
                    {% endif %}

                </div>
            {% endfor %}
        </div>
            {% endif %}

            <div>
                <a href="{% url 'pybo:comment_create_maincont' maincont.id %}" class="small"><small>댓글추가</small></a>
            </div>


        </div>


        </div>

        </div>
    </div>




</div>

{% endblock %}<!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->

<!--자바스크립트 / 게시글 삭제하기-->
<!--class는.delete, .recommend 이고, data-uri의 속성에 url이 호출된다.-->
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click',function(){
        if(confirm("정말로 삭제하실건가요?")){
            location.href=$(this).data('uri');
            }
        });

        $(".recommend").on('click' , function(){
            if(confirm("추천 하시겠습니까?")){
                location.href=$(this).data('uri');
            }
        });

    });
</script>
{% endblock %}

mysite/mysite/templates/pybo/maincont_form.html
{% extends 'base.html' %}    <!--base.html상속-->
{% block content %}           <!--base.html상속-->

<div class="container">
  <h5 class="my-3 border-bottom pb-2">저장할 사이트 추가하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류표시 start / 필수 항목임을 나타낸다.-->
    {% if form.errors %}
      <div class="alert alert-dager" role="alert">
        {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
      {% endfor %}
      </div>
    {% endif %}
    <!--오류표시 END-->
    <div class="form-group">
      <label for="subject">url사이트</label>
      <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:''}}">
    </div>

    <div class="form-group">
      <label for="word">단어</label>
      <input type="text" class="form-control" name="word" id="word" value="{{ form.word.value|default_if_none:''}}">
    </div>

    <div class="form-group">
      <label for="sentence">문장</label>
      <textarea class="form-control" name="sentence" id="sentence" rows="10" >{{ form.sentence.value|default_if_none:'' }}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>

{% endblock %}                  <!--base.html상속-->

mysite/mysite/templates/pybo/maincont_list.html
<!--main 화면 창-->

{% extends 'base.html' %}    <!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->
{% block content %}        <!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->
{% load pybo_filter %}  <!--템플릿 필터 파일 로드 / pybo_filter.py 연동-->

<div class="container my-3">

    <div class="row justify-content-between my-3">

        <div class="col-2">
            <select class="form-control sr">                        <!--정렬기능-->

                <option value="recent" {% if sr == 'recent' %}selected{% endif %} >최신순 </option>   <!--왜 띄어쓰기를 할까.. / 그래야 오류안남-->
                <option value="recommend" {% if sr == 'recommend' %}selected{% endif %} >추천순 </option>

            </select>
        </div>


        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw }}">           <!--검색기능-->
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">요약단어</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if maincont_list %}
        {% for maincont in maincont_list %}

        <!--class=text-center 로 하면 가운데 정렬, text-left로 하면 왼쪽 정렬-->
        <tr class="text-center">
            <!--전체게시물 갯수 | 시작인덱스 | 현재 인덱스 % sub를 만든다. -->
            <td>{{ maincont_list.paginator.count|sub:maincont_list.start_index|sub:forloop.counter0|add:1 }}</td>   <!--템플릿 파일 연동해서 번호 메겨줌 1.-->

            <td>
                {% if maincont.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 px-1"> {{ maincont.voter.all.count }} </span>
                {% endif %}
            </td>   <!--게시물 추천수 표시-->

            <td class="text-center">     <!--id번호에 맞게 요약단어를 나타냄 2.-->
                <a href="{%url 'pybo:detail' maincont.id %}">
                    {{maincont.word}}
                </a>
            </td>
            <td>{{ maincont.author.username }}</td>  <!--글쓴이 추가-->
            <td>{{maincont.create_date}}</td>  <!--작성일시 3.-->
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">저장된 내용이 없습니다.</td>
        </tr>
        {%endif%}
        </tbody>
    </table>

    <!-- 페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if maincont_list.has_previous %}   <!--이전 페이지가 있을 때-->
        <li class="page-item">
            <a class="page-link" data-page="{{ maincont_list.previous_page_number }}" href="#">
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">   <!--disabled로 첫 페이지 일때, 이전 페이지는 없다-->
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!--페이지 리스트ㅡ-->
        {% for page_number in maincont_list.paginator.page_range %}    <!--페이지 리스트 만들어줌 시작-->
        {% if page_number >= maincont_list.number|add:-5 and page_number <= maincont_list.number|add:5 %} <!--양쪽으로 5개씩 페이징-->
            {% if page_number == maincont_list.number %}
            <li class="page-item active" aria-current="page">           <!--active로 현재 페이지는 강조-->
                <a class="page-link" data-page="{{ page_number }}" href="#">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}  <!--양쪽 5개씩 페이징 끝-->
        {% endfor %}   <!--페이지 리스트 만들어줌 끝-->
        <!--다음페이지-->
        {% if maincont_list.has_next %}  <!--다음페이지가 있을 때-->
        <li class="page-item">
            <a class="page-link" data-page="{{ maincont_list.next_page_number }}" href="#">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled" >    <!--다음페이지가 없을때, disabled-->
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>

        {% endif %}

    </ul>
    <!--패이징처리 끝-->



    <a href="{% url 'pybo:maincont_create' %}" class="btn btn-primary"> 저장할 사이트 추가하기 </a> <!--url지정 했으니 urls.py에 path설정-->

    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw }}">          <!--검색기능 만들기-->
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="sr" name="sr" value="{{ sr }}">    <!--정렬기능만들기-->
    </form>

    <!--로그인/ 로그아웃 임시방편으로 구현 시작-->
    {% if user.is_authenticated %}    <!--로그인 상태를 판별하여 로그인여부를 나타냄-->

    <!--로그인된 상태 , user.username으로 사용자명 보여줌-->
    <a class="login" href="{% url 'common:logout' %}">{{ user.username }}로그아웃</a>
    {% else %}
    <!--로그아웃된 상태-->
    <a class="login" href="{% url 'common:login' %}">로그인</a>  <!--네비게이션 바 대신 임시방편으로-->
    {% endif %}

    <!--로그인 / 로그아웃 구현 끝-->

</div>
{% endblock %}<!--base.html을 상속한다는 뜻 / 표준 html구조를 갖춤-->

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click',function(){
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click',function(){
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();

    });

    $(".sr").on('change',function(){
        $("#sr").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
})
</script>
{% endblock %}